Adding missing Spanish text
pkp/translator pull request #26
Opened 2017-11-02 04:50 UTC by t4x0n

add two missing texts and one correction

2017-12-23 21:42 UTC, mtub commented
Looks good to me. Any thoughts, @marcbria?

2018-04-13 17:13 UTC, t4x0n commented
please, do not forget...

2018-04-16 08:27 UTC, marcbria requested changes

2018-04-16 08:27 UTC, marcbria commented on locale/es_ES/locale.xml
> +	<message key="plugins.generic.translator.localeDescription">Esta página enumera los componentes de una traducción del software y permite que el traductor modifique cada uno. Una traducción completa
Esta página enumera los **módulos** de una traducción del software y permite que el traductor modifique cada uno **de ellos**. Una traducción completa debe incluir todos **los módulos**.

2018-04-16 08:27 UTC, marcbria commented on locale/es_ES/locale.xml
> +	<message key="plugins.generic.translator.localeFile.complete">Completado ({$reference})</message>
you are right.

2018-04-16 08:27 UTC, marcbria commented on locale/es_ES/locale.xml
> +	<message key="plugins.generic.translator.miscFiles">Archivos varios</message>
thanks.

2018-04-16 18:50 UTC, t4x0n commented on locale/es_ES/locale.xml
> +	<message key="plugins.generic.translator.localeDescription">Esta página enumera los componentes de una traducción del software y permite que el traductor modifique cada uno. Una traducción completa
OK!

2018-04-16 18:51 UTC, t4x0n commented
@mtub now it is OK to merge!  thanks @marcbria for the comment!

2018-04-16 18:55 UTC, merged

2018-04-16 18:55 UTC, asmecher commented
I'll merge it & cherry-pick to `ojs-stable-3_1_1`, thanks!